import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import {
    ContrastCurve,
    DynamicColor,
    Hct,
    MaterialDynamicColors,
    SchemeTonalSpot,
    type DynamicScheme,
} from "@ktibow/material-color-utilities-nightly";

/**
 * The single source colour both schemes derive from. Changing it and rerunning this script is the
 * only supported way to reskin Docknight; nothing resolves colours at runtime.
 */
const SOURCE_HEX = "#3f6fd8";

const OUT = fileURLToPath(new URL("../../frontend/src/styles/theme.css", import.meta.url));

const material = new MaterialDynamicColors();

/**
 * m3-svelte's components read a few roles beyond the Material set: `on-on-primary` for the switch
 * handle and four `*-container-subtle` pairs. They are declared here so no component falls back to
 * an undefined custom property.
 */
function extraColors(): DynamicColor[] {
    const onOnPrimary = DynamicColor.fromPalette({
        name: "on_on_primary",
        palette: (scheme) => scheme.primaryPalette,
        background: () => material.onPrimary(),
        contrastCurve: () => new ContrastCurve(6, 6, 7, 11),
    });

    const pairs: DynamicColor[] = [onOnPrimary];

    const groups = [
        { key: "primary", palette: (scheme: DynamicScheme) => scheme.primaryPalette },
        { key: "secondary", palette: (scheme: DynamicScheme) => scheme.secondaryPalette },
        { key: "tertiary", palette: (scheme: DynamicScheme) => scheme.tertiaryPalette },
        { key: "error", palette: (scheme: DynamicScheme) => scheme.errorPalette },
    ];

    for (const group of groups) {
        const container = DynamicColor.fromPalette({
            name: `${group.key}_container_subtle`,
            palette: group.palette,
            isBackground: true,
            background: (scheme) => material.highestSurface(scheme),
            contrastCurve: () => undefined,
        });
        const onContainer = DynamicColor.fromPalette({
            name: `on_${group.key}_container_subtle`,
            palette: group.palette,
            background: () => container,
            contrastCurve: () => new ContrastCurve(6, 6, 7, 11),
        });
        pairs.push(container, onContainer);
    }

    return pairs;
}

const ROLES: DynamicColor[] = [
    ...material.allColors,
    material.shadow(),
    material.scrim(),
    ...extraColors(),
];

function hctFromHex(hex: string): Hct {
    return Hct.fromInt(0xff000000 | Number.parseInt(hex.replace("#", ""), 16));
}

function block(selector: string, scheme: DynamicScheme, colorScheme: string): string {
    const lines = ROLES.map((role) => {
        const argb = role.getArgb(scheme);
        const red = (argb >> 16) & 255;
        const green = (argb >> 8) & 255;
        const blue = argb & 255;
        return `    --m3-scheme-${role.name.replaceAll("_", "-")}: ${red} ${green} ${blue};`;
    });
    return `${selector} {\n    color-scheme: ${colorScheme};\n${lines.join("\n")}\n}`;
}

async function main(): Promise<void> {
    const source = hctFromHex(SOURCE_HEX);
    const css = [
        [
            "/*",
            " * Generated by tools/theme/generate.ts from one source colour.",
            " * Run `pnpm theme:generate` after changing SOURCE_HEX. Do not edit by hand.",
            " */",
        ].join("\n"),
        block(
            ':root, :root[data-theme="light"], ::backdrop',
            new SchemeTonalSpot(source, false, 0) as unknown as DynamicScheme,
            "light",
        ),
        block(
            ':root[data-theme="dark"]',
            new SchemeTonalSpot(source, true, 0) as unknown as DynamicScheme,
            "dark",
        ),
        "",
    ].join("\n\n");

    await writeFile(OUT, css, "utf8");
    console.log(`wrote ${OUT} with ${ROLES.length} roles`);
}

void main();
