import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { Hct, SchemeTonalSpot } from "@ktibow/material-color-utilities-nightly";
import { colors, genCSS } from "m3-svelte/etc/colors";

/**
 * Generates styles/theme.css from a single source colour. Run manually when the source colour
 * changes; the output is committed, not built at deploy time.
 */
const SOURCE_COLOR_ARGB = 0xff1a73e8; // Google Cloud Blue (#1a73e8); opaque ARGB (0xffRRGGBB)
const OUTPUT_PATH = fileURLToPath(new URL("../../frontend/src/styles/theme.css", import.meta.url));

const source = Hct.fromInt(SOURCE_COLOR_ARGB);
const light = new SchemeTonalSpot(source, false, 0);
const dark = new SchemeTonalSpot(source, true, 0);
// A blank line before the @layer at-rule, to satisfy stylelint-config-standard's
// at-rule-empty-line-before without a separate --fix pass after every regeneration.
const generated = genCSS(light, dark, colors).replace("}\n@layer", "}\n\n@layer");

const header = `/*
 * Generated by tools/theme/generate.ts from a single source colour. Do not hand-edit; change
 * SOURCE_COLOR_ARGB and re-run the script instead.
 *
 * Both schemes are expressed with light-dark(), which follows the OS colour-scheme preference
 * by default. [data-theme] on the document element overrides which branch applies, so
 * theme.svelte.ts's explicit preference always wins over the media query.
 */
`;

const themeOverride = `

[data-theme="light"] {
    color-scheme: light;
}

[data-theme="dark"] {
    color-scheme: dark;
}
`;

await writeFile(OUTPUT_PATH, header + generated + themeOverride, "utf8");
process.stdout.write(`wrote ${OUTPUT_PATH}\n`);
